# Generated by Django 3.2.9 on 2022-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identify',
            field=models.CharField(max_length=20),
        ),
    ]
