# Generated by Django 3.2.9 on 2022-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0004_alter_profile_identify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
