# Generated by Django 3.2.9 on 2022-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_data', models.CharField(max_length=50)),
                ('In', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('In_date', models.CharField(max_length=50, verbose_name='Invoice Date')),
                ('C', models.CharField(max_length=50, verbose_name='State Code')),
                ('T', models.CharField(max_length=50, verbose_name='Total')),
                ('G', models.CharField(max_length=50, verbose_name='GST Toal')),
            ],
        ),
    ]
