# Generated by Django 3.2.9 on 2022-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=50, verbose_name='Company_Name')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paisa', models.IntegerField(null=True, verbose_name='Price')),
                ('Vastu', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Biscuit_Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_data', models.CharField(max_length=50)),
                ('In', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('date', models.DateField(default='', verbose_name=' Dated')),
                ('S', models.CharField(default='', max_length=50, verbose_name='SGST')),
                ('C', models.CharField(default='', max_length=50, verbose_name='CGST')),
                ('T', models.CharField(default='', max_length=50, verbose_name='Total')),
                ('file', models.FileField(default='', upload_to='in/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.comp')),
            ],
        ),
        migrations.CreateModel(
            name='Plo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_data', models.CharField(max_length=50)),
                ('In', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('In_date', models.CharField(default='', max_length=50, verbose_name='Invoice Date')),
                ('C', models.CharField(default='', max_length=50, verbose_name='State Code')),
                ('T', models.CharField(default='', max_length=50, verbose_name='Total')),
                ('G', models.CharField(default='', max_length=50, verbose_name='GST Toal')),
                ('file', models.FileField(default='', null=True, upload_to='in/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.comp')),
            ],
        ),
    ]
