# Generated by Django 3.2.9 on 2022-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='date',
            field=models.DateField(verbose_name=' Dated'),
        ),
    ]
