# Generated by Django 3.2.9 on 2022-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_tally_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='date',
            field=models.DateField(null=True, verbose_name=' Dated'),
        ),
    ]
