# Generated by Django 3.2.9 on 2022-01-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_remove_plo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.comp'),
        ),
    ]
