# Generated by Django 3.2.9 on 2022-01-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_plo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='ipp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
